interface IFoto {
  foto: any
  descricao: any
  length: number
}
export interface AVUFormDTO {
  tipo: string
  id: string
  foto_1: IFoto[]
  foto_2: IFoto[]
  foto_3: IFoto[]
  foto_4: IFoto[]
  foto_5: IFoto[]
  foto_6: IFoto[]
  titulo: string
  responsavel: string
  cod_trein: string
  revisao: string
  matricula: string
  diretoria: string
  gerencia: string
  n_interno: string
  tipificacao: string
  polo: string
  responsavel_polo: string
  ga_envolvida: string
  data: string
  hora: string
  local: string
  empresa: string
  prev_solucao: string
  solucionado_em: string
  reincidente: string
  houve_acidente: string
  valor_prevencao: string
  base_calculo_descricao: string
  status: string
  situacao_vuneralvel_identificada: string
  risco_potencial: string
  providencias_adotadas: string
  recomendacoes_seguranca: string
  latitude: string
  longitude: string
  descricao_foto_1: string
  descricao_foto_2: string
  descricao_foto_3: string
  descricao_foto_4: string
  descricao_foto_5: string
  descricao_foto_6: string
  created_at: Date
}
